#include <stdio.h>
int main() {
char array[50000];
char *ptr=array;
++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);++ptr;++(*ptr);++(*ptr);++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++ptr;++(*ptr);++(*ptr);++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++ptr;--(*ptr);--(*ptr);--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {
++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;while (*ptr) {
--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;
++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;
--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;
++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);
++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;}++ptr;++ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {--(*ptr);--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);}}++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);++ptr;++ptr;++ptr;--(*ptr);
--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;
while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);++ptr;while (*ptr) {--(*ptr);
}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;
--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);++ptr;++(*ptr);--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;
while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;
--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);
++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;
while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);
}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
while (*ptr) {++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
}++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);
++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {
--(*ptr);}++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;++(*ptr);++(*ptr);--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;
--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--(*ptr);++ptr;++(*ptr);++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;
while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);++ptr;++ptr;}++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}
++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;
}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;
--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {
while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);
while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;
while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);++ptr;++(*ptr);--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {
++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {
++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;while (*ptr) {--(*ptr);
--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;
while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;
++(*ptr);++ptr;++ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;
while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;++(*ptr);++ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);--ptr;++(*ptr);++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;
}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;
++ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;++(*ptr);++(*ptr);--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--(*ptr);++ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;
--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);++ptr;++ptr;}++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;
--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--(*ptr);++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);
--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;
}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;
++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--(*ptr);++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {
--(*ptr);++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;
++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);
++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;
}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;++(*ptr);
++ptr;++ptr;}--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;
while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);
}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;}--ptr;++(*ptr);
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++(*ptr);--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;}++ptr;++ptr;}--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;
--(*ptr);++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;putchar(*ptr);++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;putchar(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;while (*ptr) {
++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);while (*ptr) {--(*ptr);}++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;
++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;
++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;while (*ptr) {++ptr;++ptr;
++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;
--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;}}++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;putchar(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);while (*ptr) {--(*ptr);}++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);++ptr;while (*ptr) {++ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);
++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;--ptr;--ptr;}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;while (*ptr) {++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++(*ptr);--ptr;--ptr;}++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {++ptr;while (*ptr) {--(*ptr);}--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;while (*ptr) {--ptr;--(*ptr);++ptr;--(*ptr);--ptr;--ptr;++(*ptr);++ptr;++ptr;}--ptr;while (*ptr) {--(*ptr);++ptr;++(*ptr);--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}--ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;
++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++(*ptr);--ptr;}}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
--(*ptr);--ptr;--ptr;while (*ptr) {--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}++(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;
++ptr;++ptr;++ptr;}++ptr;while (*ptr) {--(*ptr);}++(*ptr);--ptr;}}++(*ptr);++ptr;while (*ptr) {--(*ptr);--ptr;while (*ptr) {++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;while (*ptr) {--(*ptr);}--ptr;--ptr;--ptr;++(*ptr);++(*ptr);++(*ptr);++(*ptr);
++(*ptr);while (*ptr) {--(*ptr);while (*ptr) {--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;}++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;++ptr;--(*ptr);--ptr;--ptr;--ptr;--ptr;--ptr;--ptr;while (*ptr) {--ptr;--ptr;--ptr;--ptr;
--ptr;--ptr;--ptr;--ptr;--ptr;}}++ptr;++ptr;++ptr;}
return 0;
}